import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface ContactFormData {
  name: string;
  email: string;
  phone: string;
  company: string;
  service: string;
  message: string;
}

export const generateContactPDF = async (formData: ContactFormData): Promise<Blob> => {
  const pdf = new jsPDF();
  
  // Set font sizes and colors
  const titleColor = [0, 51, 102]; // Dark blue
  const textColor = [0, 0, 0]; // Black
  const accentColor = [102, 102, 102]; // Gray
  
  // Add header
  pdf.setFontSize(24);
  pdf.setTextColor(titleColor[0], titleColor[1], titleColor[2]);
  pdf.text('Contact Form Submission', 20, 30);
  
  // Add date
  pdf.setFontSize(10);
  pdf.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  const submissionDate = new Date().toLocaleString();
  pdf.text(`Submitted: ${submissionDate}`, 20, 40);
  
  // Add line separator
  pdf.setDrawColor(200, 200, 200);
  pdf.line(20, 45, 190, 45);
  
  // Add contact information
  let yPosition = 60;
  pdf.setFontSize(12);
  pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
  
  // Name
  pdf.setFont('helvetica', 'bold');
  pdf.text('Full Name:', 20, yPosition);
  pdf.setFont('helvetica', 'normal');
  pdf.text(formData.name, 60, yPosition);
  yPosition += 15;
  
  // Email
  pdf.setFont('helvetica', 'bold');
  pdf.text('Email Address:', 20, yPosition);
  pdf.setFont('helvetica', 'normal');
  pdf.text(formData.email, 60, yPosition);
  yPosition += 15;
  
  // Phone
  pdf.setFont('helvetica', 'bold');
  pdf.text('Phone Number:', 20, yPosition);
  pdf.setFont('helvetica', 'normal');
  pdf.text(formData.phone || 'Not provided', 60, yPosition);
  yPosition += 15;
  
  // Company
  pdf.setFont('helvetica', 'bold');
  pdf.text('Company Name:', 20, yPosition);
  pdf.setFont('helvetica', 'normal');
  pdf.text(formData.company || 'Not provided', 60, yPosition);
  yPosition += 15;
  
  // Service
  pdf.setFont('helvetica', 'bold');
  pdf.text('Service Interested In:', 20, yPosition);
  pdf.setFont('helvetica', 'normal');
  const serviceText = formData.service ? getServiceDisplayName(formData.service) : 'Not specified';
  pdf.text(serviceText, 60, yPosition);
  yPosition += 20;
  
  // Message section
  pdf.setFont('helvetica', 'bold');
  pdf.text('Project Details:', 20, yPosition);
  yPosition += 10;
  
  // Handle multi-line message
  pdf.setFont('helvetica', 'normal');
  const splitMessage = pdf.splitTextToSize(formData.message, 170);
  pdf.text(splitMessage, 20, yPosition);
  
  // Add footer
  const pageHeight = pdf.internal.pageSize.height;
  pdf.setFontSize(8);
  pdf.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  pdf.text('Generated by Ranbidge Services Contact Form', 20, pageHeight - 10);
  pdf.text('www.ranbidge.com', 150, pageHeight - 10);
  
  return new Promise((resolve) => {
    pdf.output('blob').then((blob) => {
      resolve(blob);
    });
  });
};

const getServiceDisplayName = (serviceValue: string): string => {
  const serviceMap: { [key: string]: string } = {
    'web-development': 'Web Development',
    'mobile-development': 'Mobile App Development',
    'software-development': 'Software Development',
    'ui-ux-design': 'UI/UX Design',
    'digital-marketing': 'Digital Marketing',
    'it-consulting': 'IT Consulting',
    'other': 'Other'
  };
  return serviceMap[serviceValue] || serviceValue;
};
